apiVersion: v1
kind: Service
metadata:
  name: feedback-app-api-service
spec:
  selector:
    app: feedback-app-api
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-app-api
  template:
    metadata:
      labels:
        app: feedback-app-api
        environment: test
    spec:
      containers:
      - name: feedback-app-backend-api
        image: galaataman/feedback-app:v4.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: feedback-app-secret
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: feedback-app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: feedback-app-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feedback-app-secret
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: feedback-app-config
              key: DB_PORT
        livenessProbe:
          httpGet:
            path: /feedback 
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1